<a href="https://colab.research.google.com/github/RG-pygit/RG-pygit/blob/main/training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pymysql


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 43 kB 1.4 MB/s 


In [ ]:
import pymysql


ModuleNotFoundError: ignored

In [ ]:
pip install pymysql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 43 kB 893 kB/s 


In [ ]:
import pymysql


In [ ]:
import numpy as np

In [ ]:
x=numpy.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
print(x)
print(x[1,...])
print(x[...,2])
print(x[...,2:])


[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
[5 6 7 8]
[3 7 2]
[[3 4]
 [7 8]
 [2 3]]


In [ ]:
y=x.reshape(2,6)
print(y)
print(x)

[[1 2 3 4 5 6]
 [7 8 9 1 2 3]]
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


In [ ]:
x.shape=(6,2)

In [ ]:
a=np.arange(2,22,2)
a.shape=(5,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
a.shape=(5,2)

In [ ]:
print(a)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [ ]:
z=np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
z=np.ones((3,4))
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
c=np.linspace(11,40,9)
print(c)

[11.    14.625 18.25  21.875 25.5   29.125 32.75  36.375 40.   ]


In [ ]:
x=np.array([2,3,4,5,6,7,8])
y=slice(2,9,2)
print(x[y])

[4 6 8]


In [ ]:
x=np.array([[6,6,6],[2,2,2],[3,2,5]])
y=np.array([[2,3,2],[1,1,2],[2,1,3]])

 
print(x,y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
 

[[6 6 6]
 [2 2 2]
 [3 2 5]] [[2 3 2]
 [1 1 2]
 [2 1 3]]
[[8 9 8]
 [3 3 4]
 [5 3 8]]
[[4 3 4]
 [1 1 0]
 [1 1 2]]
[[12 18 12]
 [ 2  2  4]
 [ 6  2 15]]
[[3.         2.         3.        ]
 [2.         2.         1.        ]
 [1.5        2.         1.66666667]]
[[0 0 0]
 [0 0 0]
 [1 0 2]]


In [ ]:
x=np.array([[6,6,6],[2,2,2],[3,2,5]])
print(x)
x.flatten(order='F')

[[6 6 6]
 [2 2 2]
 [3 2 5]]


array([6, 2, 3, 6, 2, 2, 6, 2, 5])

In [ ]:
print(x.T)

[[6 2 3]
 [6 2 2]
 [6 2 5]]


In [ ]:
import numpy as np
x=np.array([[6,6,6],[2,2,2],
            [3,2,5]])

 

a=[[5,6,7],[6,7,8],[4,5,6]]
y=np.concatenate((x,a),axis=1)
print(y)

[[6 6 6 5 6 7]
 [2 2 2 6 7 8]
 [3 2 5 4 5 6]]


In [ ]:
a=[[5,6,7],[6,7,8],[4,5,6]]
y=np.concatenate((x,a),axis=0)
print(y)

[[6 6 6]
 [2 2 2]
 [3 2 5]
 [5 6 7]
 [6 7 8]
 [4 5 6]]


In [ ]:
x=np.array([[5,8],[3,4]])

 
print(x)
y=np.insert(x,1,30)
print(y)

[[5 8]
 [3 4]]
[ 5 30  8  3  4]


In [ ]:
x=np.array([[5,8],[3,4]])

 
print(x)
y=np.insert(x,1,30,axis=1)
print(y)

[[5 8]
 [3 4]]
[[ 5 30  8]
 [ 3 30  4]]


In [ ]:
x= np.array([32,54,5,54,51,32,76,87,5,61])

 

y=np.unique(x)
print(y)

[ 5 32 51 54 61 76 87]


In [ ]:
print(x)

[32 54  5 54 51 32 76 87  5 61]


In [ ]:
x=np.array([[1,2],[3,4]])

 

print(np.amin(x)) #min
print(np.amin(x,1)) #min row wise
print(np.amin(x,0)) #min col wise
print(np.amax(x)) #max
print(np.amax(x,1)) #max row wise
print(np.amax(x,0)) #max col wise

1
[1 3]
[1 2]
4
[2 4]
[3 4]


In [ ]:
x=np.array([[0,0],[3,0]])

 

print(np.nonzero(x))

(array([1]), array([0]))


In [ ]:
x=np.array([[23,6],[13,3]])
#row wise
print(np.sort(x))
#col wise
print(np.sort(x,axis=0))

[[ 6 23]
 [ 3 13]]
[[13  3]
 [23  6]]


In [6]:
import pandas as pd
s=pd.Series([4,5,6,7],index=['a','b','c','d'])
s['a']=5
s

a    5
b    5
c    6
d    7
dtype: int64

In [7]:
d={'rollno':1,'name':'rosy','marks':34}

In [11]:
e=pd.Series(d,index=['name','rollno','marks'])
e

name      rosy
rollno       1
marks       34
dtype: object

In [13]:
d=pd.Series(5,index=[1,2,3,4])
d

1    5
2    5
3    5
4    5
dtype: int64

In [16]:
p=pd.DataFrame()
print(p)

Empty DataFrame
Columns: []
Index: []


In [22]:
a=[4,5,6,7]
b=pd.DataFrame(a)
print(b)

   0
0  4
1  5
2  6
3  7


In [30]:
s=[['rosy',22],['tal',26]]
b=pd.DataFrame(s,columns=['name','age'],index=[1,2])
b


name  age
1  rosy   22
2   tal   26

In [31]:
d={'rollno':1,'name':'rosy','marks':34}
f=pd.DataFrame(d)
f

ValueError: ignored

In [38]:
d={'empno':101,
'name':'aa',
'salary':65000}

df=pd.DataFrame(d,index=[1])
print(df)

   empno name  salary
1    101   aa   65000


In [40]:
df=pd.read_csv('transaction_data.csv')
print(df.head())

     UserId  TransactionId               TransactionTime  ItemCode  \
0  278166.0        6355745  Sat Feb 02 12:50:00 IST 2019    465549   
1  337701.0        6283376  Wed Dec 26 09:06:00 IST 2018    482370   
2  267099.0        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
3  380478.0        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
4  331884.0        6223569  Sun Nov 18 11:14:00 IST 2018    461622   

                    ItemDescription  NumberOfItemsPurchased  CostPerItem  \
0  FAMILY ALBUM WHITE PICTURE FRAME                       6        11.73   
1             LONDON BUS COFFEE MUG                       3         3.52   
2                               NaN                      72         0.90   
3       UNION JACK FLAG LUGGAGE TAG                       3          NaN   
4          PACK OF 12 SUKI TISSUES                       72         0.54   

          Country  
0  United Kingdom  
1  United Kingdom  
2          France  
3  United Kingdom  
4  United Kingdom  


In [44]:
df.dtypes

UserId                    float64
TransactionId               int64
TransactionTime            object
ItemCode                    int64
ItemDescription            object
NumberOfItemsPurchased      int64
CostPerItem               float64
Country                    object
dtype: object

In [54]:
df[2:7]

UserId  TransactionId               TransactionTime  ItemCode  \
2  267099.0        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
3  380478.0        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
4  331884.0        6223569  Sun Nov 18 11:14:00 IST 2018    461622   
5  335580.0        6031883  Mon Jun 11 11:05:00 IST 2018    476028   
6  364308.0        6257163  Tue Dec 11 07:39:00 IST 2018    434028   

                   ItemDescription  NumberOfItemsPurchased  CostPerItem  \
2                              NaN                      72         0.90   
3      UNION JACK FLAG LUGGAGE TAG                       3          NaN   
4         PACK OF 12 SUKI TISSUES                       72         0.54   
5                PINK BABY BUNTING                     150         3.52   
6  DISCO BALL CHRISTMAS DECORATION                      72          NaN   

          Country  
2          France  
3  United Kingdom  
4  United Kingdom  
5  United Kingdom  
6  United Kingdom

In [57]:

df['TotalBill']=df['CostPerItem']*df['NumberOfItemsPurchased']
print(df[['TotalBill','CostPerItem','NumberOfItemsPurchased']].head(10))

   TotalBill  CostPerItem  NumberOfItemsPurchased
0      70.38        11.73                       6
1      10.56         3.52                       3
2      64.80         0.90                      72
3        NaN          NaN                       3
4      38.88         0.54                      72
5     528.00         3.52                     150
6        NaN          NaN                      72
7     132.12        22.02                       6
8     102.00         3.40                      30
9      34.35        11.45                       3


In [60]:
print(df.iloc[0:3,0:3])

     UserId  TransactionId               TransactionTime
0  278166.0        6355745  Sat Feb 02 12:50:00 IST 2019
1  337701.0        6283376  Wed Dec 26 09:06:00 IST 2018
2  267099.0        6385599  Fri Feb 15 09:45:00 IST 2019


In [63]:
df=pd.read_csv('transaction_data_index.csv',index_col='SrNo')
s=df.loc['A0003']
print(s)

UserId                                        267099.0
TransactionId                                  6385599
TransactionTime           Fri Feb 15 09:45:00 IST 2019
ItemCode                                        490728
ItemDescription                                    NaN
NumberOfItemsPurchased                              72
CostPerItem                                        0.9
Country                                         France
Name: A0003, dtype: object


In [67]:
df=pd.read_csv('transaction_data.csv')
dt=df[(df['Country']=='India')& (df['CostPerItem']>14)]
print(dt)

       UserId  TransactionId               TransactionTime  ItemCode  \
57       -1.0        6314814  Mon Jan 14 11:33:00 IST 2019   1765638   
123      -1.0        5914326  Fri Feb 18 14:36:00 IST 2028    446418   
262  291480.0        6111534  Sat Aug 18 06:09:00 IST 2018    470883   
265      -1.0        6395829  Tue Feb 19 12:30:00 IST 2019    481761   
287  365799.0        6005065  Sun May 20 07:44:00 IST 2018    479472   

                      ItemDescription  NumberOfItemsPurchased  CostPerItem  \
57   SET/4 WHITE RETRO STORAGE CUBES                        3        80.45   
123        VICTORIAN SEWING BOX LARGE                       3        35.18   
262          REGENCY CAKESTAND 3 TIER                       3        17.60   
265      CHRISTMAS LIGHTS 10 REINDEER                       6        22.95   
287         BROCANTE SHELF WITH HOOKS                       6        14.84   

    Country  
57    India  
123   India  
262   India  
265   India  
287   India  


In [69]:
df.insert(1,'GST',df['CostPerItem']*0.18)
print(df.head(10))

ValueError: ignored

In [70]:
df.head()

UserId     GST  TransactionId               TransactionTime  ItemCode  \
0  278166.0  2.1114        6355745  Sat Feb 02 12:50:00 IST 2019    465549   
1  337701.0  0.6336        6283376  Wed Dec 26 09:06:00 IST 2018    482370   
2  267099.0  0.1620        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
3  380478.0     NaN        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
4  331884.0  0.0972        6223569  Sun Nov 18 11:14:00 IST 2018    461622   

                    ItemDescription  NumberOfItemsPurchased  CostPerItem  \
0  FAMILY ALBUM WHITE PICTURE FRAME                       6        11.73   
1             LONDON BUS COFFEE MUG                       3         3.52   
2                               NaN                      72         0.90   
3       UNION JACK FLAG LUGGAGE TAG                       3          NaN   
4          PACK OF 12 SUKI TISSUES                       72         0.54   

          Country  
0  United Kingdom  
1  United Kingdom  
2          France  
3  United Kingdom  
4  United Kingdom

In [73]:
df['CostPerItem'].fillna(0,inplace=True)

In [74]:
df.head()

UserId     GST  TransactionId               TransactionTime  ItemCode  \
0  278166.0  2.1114        6355745  Sat Feb 02 12:50:00 IST 2019    465549   
1  337701.0  0.6336        6283376  Wed Dec 26 09:06:00 IST 2018    482370   
2  267099.0  0.1620        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
3  380478.0     NaN        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
4  331884.0  0.0972        6223569  Sun Nov 18 11:14:00 IST 2018    461622   

                    ItemDescription  NumberOfItemsPurchased  CostPerItem  \
0  FAMILY ALBUM WHITE PICTURE FRAME                       6        11.73   
1             LONDON BUS COFFEE MUG                       3         3.52   
2                               NaN                      72         0.90   
3       UNION JACK FLAG LUGGAGE TAG                       3         0.00   
4          PACK OF 12 SUKI TISSUES                       72         0.54   

          Country  
0  United Kingdom  
1  United Kingdom  
2          France  
3  United Kingdom  
4  United Kingdom

In [77]:
df=pd.read_csv('transaction_data.csv')
df['CostPerItem'].fillna(df['CostPerItem'].mean(),inplace=True)

In [78]:
df.head()

UserId  TransactionId               TransactionTime  ItemCode  \
0  278166.0        6355745  Sat Feb 02 12:50:00 IST 2019    465549   
1  337701.0        6283376  Wed Dec 26 09:06:00 IST 2018    482370   
2  267099.0        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
3  380478.0        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
4  331884.0        6223569  Sun Nov 18 11:14:00 IST 2018    461622   

                    ItemDescription  NumberOfItemsPurchased  CostPerItem  \
0  FAMILY ALBUM WHITE PICTURE FRAME                       6    11.730000   
1             LONDON BUS COFFEE MUG                       3     3.520000   
2                               NaN                      72     0.900000   
3       UNION JACK FLAG LUGGAGE TAG                       3     4.887199   
4          PACK OF 12 SUKI TISSUES                       72     0.540000   

          Country  
0  United Kingdom  
1  United Kingdom  
2          France  
3  United Kingdom  
4  United Kingdom

In [83]:
df1=pd.read_csv('ordered_data.csv')
print(pd.merge(df,df1,on='UserId'))

      UserId  TransactionId               TransactionTime  ItemCode  \
0   278166.0        6355745  Sat Feb 02 12:50:00 IST 2019    465549   
1   278166.0        6088357  Sun Jul 29 08:38:00 IST 2018    487284   
2   337701.0        6283376  Wed Dec 26 09:06:00 IST 2018    482370   
3   267099.0        6385599  Fri Feb 15 09:45:00 IST 2019    490728   
4   380478.0        6044973  Fri Jun 22 07:14:00 IST 2018    459186   
5   380478.0        5976399  Sat Apr 21 08:05:00 IST 2018   1784370   
6   380478.0        6161375  Wed Sep 26 06:44:00 IST 2018    471303   
7   331884.0        6223569  Sun Nov 18 11:14:00 IST 2018    461622   
8   335580.0        6031883  Mon Jun 11 11:05:00 IST 2018    476028   
9   364308.0        6257163  Tue Dec 11 07:39:00 IST 2018    434028   
10  262269.0        5945093  Wed Mar 21 09:13:00 IST 2018    474726   

                      ItemDescription  NumberOfItemsPurchased  CostPerItem  \
0    FAMILY ALBUM WHITE PICTURE FRAME                       6    11.7

In [82]:
df1.head()

UserId   Name
0  278166    Raj
1  337701   John
2  267099   Ravi
3  380478  Rahul
4  331884  Akram

In [84]:
print(df.sort_values('CostPerItem',ascending=False))

       UserId  TransactionId               TransactionTime  ItemCode  \
57       -1.0        6314814  Mon Jan 14 11:33:00 IST 2019   1765638   
239  275415.0        6278866  Mon Dec 24 08:42:00 IST 2018   1765638   
123      -1.0        5914326  Fri Feb 18 14:36:00 IST 2028    446418   
127  266301.0        5970085  Sat Apr 14 11:36:00 IST 2018        -1   
93       -1.0        5918781  Tue Feb 20 10:09:00 IST 2018    478317   
..        ...            ...                           ...       ...   
284  346584.0        6339586  Sat Jan 26 11:18:00 IST 2019    469119   
217  329721.0        6202999  Fri Nov 02 08:36:00 IST 2018   1789284   
121      -1.0        6108674  Tue Aug 14 07:12:00 IST 2018   1780905   
124      -1.0        5914040  Fri Feb 18 11:31:00 IST 2028    445872   
214      -1.0        6297863  Sat Jan 05 12:06:00 IST 2019   1782417   

                      ItemDescription  NumberOfItemsPurchased  CostPerItem  \
57   SET/4 WHITE RETRO STORAGE CUBES                     

In [87]:
import numpy as np
df=pd.read_csv('train_pivot.csv')
table=pd.pivot_table(df,index=['Sex','Pclass'],aggfunc={'Age':np.mean,'Survived':np.sum})
print(table)

                     Age  Survived
Sex    Pclass                     
female 1       34.611765        91
       2       28.722973        70
       3       21.750000        72
male   1       41.281386        45
       2       30.740707        17
       3       26.507589        47
